### ISSUE TITLE
Strange error coming from base-x package

### ISSUE THREAD

**Issue by vongohren** [uport-project/react-native-uport-connect#10]
Im using the new version and everything seemed fine, but there is a strange error when loading coming from a dependency. I searched through the codebase of nodemodules and found only one place it was use, in base-x packaged.

```
npm ls base-x
diwala-mobile@0.0.1 /Users/snorre/code/diwala/cert-platform/packages/mobile
└─┬ react-native-uport-connect@1.0.1
  ├─┬ uport-connect@1.0.1
  │ ├─┬ mnid@0.1.1
  │ │ └── base-x@3.0.5
  │ └─┬ uport-lite@1.0.2
  │   └── base-x@3.0.5  deduped
  └─┬ uport-credentials@1.0.1
    └─┬ muport-did-resolver@0.1.3
      └─┬ bs58@4.0.1
        └── base-x@3.0.5  deduped
```

The error is 
`undefined is not a function (evaluation 'BASE_MAP.fill(255)')`

Have you seen this before @simonas-notcat ?

![screenshot_20181119-172821](https://user-images.githubusercontent.com/1012055/48720734-9227f180-ec20-11e8-91fd-eb3cd2319ecc.png)

**Comment by vongohren** [comment]
I tried running the demo, and that pulls in a version lower, 3.0.4 and that works fine. So just thinking that might be a problem? Since the library has not been updated in one year.

**Comment by simonas-notcat** [comment]
@rmw2 as I understand this problem originates in our libs. Can you take a look?

**Comment by simonas-notcat** [comment]
@vongohren  I cannot reproduce base-x issue that you are having. First I tried deleting `yarn.lock` file from https://github.com/uport-project/uport-react-native-demo and running `yarn`. This installed `base-x@3.0.5`. And I was not getting any errors. Then I tried creating react-native app from scratch and I did not get any errors there as well: https://github.com/simonas-notcat/basextest

**Comment by vongohren** [comment]
Thats strange, because it was quite consistent for me with npm ls base-x hitting 3.0.4 on the demo app, and my hit 3.0.5. But when I forced it down to 3.0.4, it worked. So not sure what to say :P Other than that got me past that problem

**Comment by simonas-notcat** [comment]
@vongohren from https://github.com/simonas-notcat/basextest

```
npm ls base-x
baseXTest@0.0.1 /Users/simonas/dev/tmp/baseXTest
└─┬ react-native-uport-connect@1.0.1
  ├─┬ uport-connect@1.0.2
  │ ├─┬ mnid@0.1.1
  │ │ └── base-x@3.0.5
  │ └─┬ uport-lite@1.0.2
  │   └── base-x@3.0.5  deduped
  └─┬ uport-credentials@1.0.2
    └─┬ muport-did-resolver@0.1.3
      └─┬ bs58@4.0.1
        └── base-x@3.0.5  deduped
```

Have you tried running this example? I'm not getting any errors.

**Comment by vongohren** [comment]
So the problem exists here aswell.
![screenshot_20181130-105225](https://user-images.githubusercontent.com/1012055/49276288-1daa4980-f48f-11e8-910b-14d96afb4e04.png)

I have to update to a higher node because of this
<img width="1082" alt="screenshot 2018-11-30 at 10 52 00" src="https://user-images.githubusercontent.com/1012055/49276111-834a0600-f48e-11e8-9af8-889659337a2b.png">

And this my env
<img width="1089" alt="screenshot 2018-11-30 at 10 52 20" src="https://user-images.githubusercontent.com/1012055/49276188-cefcaf80-f48e-11e8-9a66-9800cfa04e19.png">

**Comment by RNHaoHao** [comment]
@vongohren  Have you solved this problem? I've also met this problem recently. When adding eosjs dependencies to RN

**Comment by vongohren** [comment]
@RNHaoHao yes, this problem is solved on my end. I went into the lockfile and adjusted the base-x dependency to base-x@3.0.4. You need to adjust the number in the lockfile, and might need to change the SHA image by going into the npm package link and find the sha for 3.0.4. But you will se that the integrity doesnt make sense when installing by just 3.0.4

**Comment by simonas-notcat** [comment]
@vongohren @RNHaoHao we have fixed this issue in our upcoming release https://github.com/uport-project/react-native-uport-connect/pull/16

Can you try it out and see if it solves the problem for you?

Latest demo app is here: https://github.com/uport-project/uport-react-native-demo/pull/8

**Comment by rantwijk** [comment]
> @vongohren @RNHaoHao we have fixed this issue in our upcoming release #16
> 
> Can you try it out and see if it solves the problem for you?
> 
> Latest demo app is here: [uport-project/uport-react-native-demo#8](https://github.com/uport-project/uport-react-native-demo/pull/8)

I faced the same issue and tried the pull request. It does not seem to fix the issue, as it still pops up as soon as the app is launched (`undefined is not a function(evaluating 'BASE_MAP.fill(255)')`). The temporary fix I've been using is to remove the line `BASE_MAP.fill(255)` line in index.js of the base-x package and filling the array with 255 manually (simple for loop).

**Comment by vongohren** [comment]
@simonas-notcat I will try it out a bit later but seems like the problem persists for someone ☝️

**Comment by simonas-notcat** [comment]
@rantwijk can you try clearing yarn cache?
```
npm ls base-x
yarn cache clean
yarn
npm ls base-x
```

What output do you get by running this?

**Comment by simonas-notcat** [comment]
Fixed in https://github.com/uport-project/react-native-uport-connect/pull/16
